baseurl = "https://www.dataforestblog.com"
title = "Data Forest"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "John Wood"

[Privacy]

[Privacy.disqus]
    disable = true

[Author]
    name = "John Wood"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/XXX"
    linkedin = "https://linkedin.com/in/XXX/"
    twitter = "https://twitter.com/XXX"
    email = "jmw.home@gmail.com"
    shareTwitter = true
    shareFacebook = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4